import "./globals.css";
import { Inter } from "next/font/google";
import SideBar from "@/components/SideBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='block sm:flex'>
          <div className="w-full fixed z-20 top-0 sm:w-64 mt-0"><SideBar /></div>
          <div className="flex justify-center top-96 sm:top-0 sm:ms-64 sm:w-full relative">{children}</div>
        </div>
      </body>
    </html>
  );
}
